// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type faculty = Collections['faculty']['schema']['_output']
export declare const faculty: faculty[]

export type courses = Collections['courses']['schema']['_output']
export declare const courses: courses[]
